<template>
  <div class="loading-container" v-if="show">
    <div class="loadingio-spinner-eclipse-hyj11p3vilq"><div class="ldio-88mdma17w4p">
    <div></div>
    </div></div>
  </div>
</template>

<script>
export default {
  name: "LoadingCom",
  props: [
      "show"
  ]
}
</script>

<style scoped>
  .loading-container {
    position: absolute;
    top: 0;
    width: 100%;
    height: 100%;
    backdrop-filter: blur(1px);
    z-index: 1000000;
  }
  .loading-container img {
    width: 52px;
    height: 52px;
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
  }
  @keyframes ldio-88mdma17w4p {
  0% { transform: rotate(0deg) }
  50% { transform: rotate(180deg) }
  100% { transform: rotate(360deg) }
}
.ldio-88mdma17w4p div {
  position: absolute;
  animation: ldio-88mdma17w4p 0.78s linear infinite;
  width: 159.12px;
  height: 159.12px;
  top: 22.44px;
  left: 22.44px;
  border-radius: 50%;
  box-shadow: 0 4.488px 0 0 #e15b64;
  transform-origin: 79.56px 81.804px;
}
.loadingio-spinner-eclipse-hyj11p3vilq {
  width: 204px;
  height: 204px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-88mdma17w4p {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-88mdma17w4p div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>