<template>
  <div class="loadingio-spinner-ellipsis-zju33sz6uu loading">
    <div class="ldio-0kxuwhok2lwg">
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
    </div>
  </div>
</template>

<script>
export default {
  name: "LoadingInline",
  props: {
    scale: {
      type: Number,
      default: 1,
    }
  },
  data() {
    return {
      scaleSize: 'scale(' + this.scale + ')'
    }
  },
}
</script>
<style scoped>
.loading {
  z-index: 1000000;
  position: absolute;
  margin: auto;
  left: 0;
  right: 0;
  top: 0;
  bottom: 0;
}
@keyframes ldio-0kxuwhok2lwg {
   0% { transform: translate(5.699999999999999px,44.459999999999994px) scale(0); }
  25% { transform: translate(5.699999999999999px,44.459999999999994px) scale(0); }
  50% { transform: translate(5.699999999999999px,44.459999999999994px) scale(1); }
  75% { transform: translate(44.459999999999994px,44.459999999999994px) scale(1); }
 100% { transform: translate(83.22px,44.459999999999994px) scale(1); }
}
@keyframes ldio-0kxuwhok2lwg-r {
   0% { transform: translate(83.22px,44.459999999999994px) scale(1); }
 100% { transform: translate(83.22px,44.459999999999994px) scale(0); }
}
@keyframes ldio-0kxuwhok2lwg-c {
   0% { background: #00bcd4 }
  25% { background: #009688 }
  50% { background: #ff9800 }
  75% { background: #673ab7 }
 100% { background: #00bcd4 }
}
.ldio-0kxuwhok2lwg div {
  position: absolute;
  width: 25.08px;
  height: 25.08px;
  border-radius: 50%;
  transform: translate(44.459999999999994px,44.459999999999994px) scale(1);
  background: #00bcd4;
  animation: ldio-0kxuwhok2lwg 1.408450704225352s infinite cubic-bezier(0,0.5,0.5,1);
}
.ldio-0kxuwhok2lwg div:nth-child(1) {
  background: #673ab7;
  transform: translate(83.22px,44.459999999999994px) scale(1);
  animation: ldio-0kxuwhok2lwg-r 0.352112676056338s infinite cubic-bezier(0,0.5,0.5,1), ldio-0kxuwhok2lwg-c 1.408450704225352s infinite step-start;
}.ldio-0kxuwhok2lwg div:nth-child(2) {
  animation-delay: -0.352112676056338s;
  background: #00bcd4;
}.ldio-0kxuwhok2lwg div:nth-child(3) {
  animation-delay: -0.704225352112676s;
  background: #673ab7;
}.ldio-0kxuwhok2lwg div:nth-child(4) {
  animation-delay: -1.056338028169014s;
  background: #ff9800;
}.ldio-0kxuwhok2lwg div:nth-child(5) {
  animation-delay: -1.408450704225352s;
  background: #009688;
}
.loadingio-spinner-ellipsis-zju33sz6uu {
  width: 114px;
  height: 114px;
  display: inline-block;
  overflow: hidden;
  transform: v-bind(scaleSize);
}
.ldio-0kxuwhok2lwg {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-0kxuwhok2lwg div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>