<template>
  <div class="loadingio-spinner-eclipse-hyj11p3vilq" v-show="showLoading">
      <div class="ldio-88mdma17w4p">
        <div></div>
      </div>
    </div>
</template>

<script>
export default {
  name: "LoadingCom",
  data() {
    return {
      showLoading: false,
    }
  },
  methods: {
    show() {
      this.showLoading = true
    },
    close() {
      this.showLoading = false
    }
  }
}
</script>

<style scoped>
  .loading {
    z-index: 1000000;
    /* transform: scale(0.5); */
    position: absolute;
    margin: auto;
    left: 0;
    right: 0;
    top: 0;
    bottom: 0;
  }
  @keyframes ldio-88mdma17w4p {
    0% { transform: rotate(0deg) }
    50% { transform: rotate(180deg) }
    100% { transform: rotate(360deg) }
  }
  .ldio-88mdma17w4p div {
    position: absolute;
    animation: ldio-88mdma17w4p 0.78s linear infinite;
    width: 159.12px;
    height: 159.12px;
    top: 22.44px;
    left: 22.44px;
    border-radius: 50%;
    box-shadow: 0 4.488px 0 0 #e15b64;
    transform-origin: 79.56px 81.804px;
  }
  .loadingio-spinner-eclipse-hyj11p3vilq {
    transform: scale(0.7);
    position: absolute;
    margin: auto;
    left: 0;
    right: 0;
    top: 0;
    bottom: 0;
    width: 204px;
    height: 204px;
    display: inline-block;
    overflow: hidden;
    background: none;
  }
  .ldio-88mdma17w4p {
    width: 70%;
    height: 70%;
    position: relative;
    transform: translateZ(0) scale(1);
    backface-visibility: hidden;
    transform-origin: 0 0; /* see note above */
  }
  .ldio-88mdma17w4p div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>