export default [
    {
        id: 1, type: 'folder', size: 70, name:"系统工具", apps: [
            {
                id: 2,
                type: 'app',
                size: 70,
                name: "历史记录",
                icon:"../../../assets/images/app/history.png",
                link:"",
                app: "history"
            },
            {
                id: 3,
                type: 'app',
                size: 70,
                name: "插件管理",
                icon:"../../../assets/images/app/extension.png",
                link:"chrome://history/",
                app: "extension"
            },
        ]
    },
    {
        id: 22,
        type: 'app',
        name: "切壁纸",
        icon: "../../../assets/images/app/wallpaper.png",
        app: 'wallpaper',
        params: {
            width: 40,
        }
    },
    {
        id: 23,
        type: 'app',
        size: 70,
        name: "计算器",
        icon: "../../../assets/images/app/calculator.png",
        app: 'calculator',
    },
    {
        id: 24,
        type: 'app',
        size: 70,
        name: "AppStore",
        icon: "../../../assets/images/app/appstore.png",
        app: 'appstore',
    },
    {
        id: 25,
        type: 'app',
        size: 70,
        name: "备忘录",
        icon: "../../../assets/images/app/note.png",
        app: 'note',
    },
    {
        id: 26,
        type: 'app',
        size: 70,
        name: "超级搜索",
        icon: "../../../assets/images/app/searcher.png",
        app: 'searcher',
    },
    {
        id: 27,
        type: 'app',
        size: 70,
        name: "翻译",
        icon: "../../../assets/images/app/translate.png",
        app: 'translate',
    },
    {
        id: 28,
        type: 'app',
        size: 70,
        name: "JSON格式化",
        icon: "../../../assets/images/app/json.png",
        app: 'json',
    },
    {
        id: 29,
        type: 'app',
        size: 70,
        name: "热门短视频",
        icon: "../../../assets/images/app/short_video.png",
        app: 'video',
    },
    {
        id: 30,
        type: 'app',
        name: "天气",
        icon: "../../../assets/images/app/weather.png",
        app: 'weather',
    },
    {
        id: 31,
        type: 'app',
        name: "天气",
        icon: "../../../assets/images/app/weather.png",
        app: 'weather',
    },
    {
        id: 32,
        type: 'app',
        name: "天气",
        icon: "../../../assets/images/app/weather.png",
        app: 'weather',
    },
    {
        id: 33,
        type: 'app',
        name: "天气",
        icon: "../../../assets/images/app/weather.png",
        app: 'weather',
    },
    {
        id: 34,
        type: 'app',
        name: "天气",
        icon: "../../../assets/images/app/weather.png",
        app: 'weather',
    },
    {
        id: 30,
        type: 'app',
        name: "天气",
        icon: "../../../assets/images/app/weather.png",
        app: 'weather',
    },
    {
        id: 35,
        type: 'app',
        name: "天气",
        icon: "../../../assets/images/app/weather.png",
        app: 'weather',
    },
]